version: '3.7'

services:

  fedbird_1:
    environment:
      - CLIENT_NAME=${CLIENT_NAME}_1
    image: "fedbird:latest"
    env_file:
      - ./project.env
    working_dir: /app
    command: /bin/bash -c "fedn run client -d ${FEDN_REDUCER_HOST} -p ${FEDN_REDUCER_PORT} -n ${CLIENT_NAME}_1 -t ${FEDN_ALLIANCE_ADMIN_AUTH_TOKEN}" 
    volumes:
      - ./${COMPONENT_PATH}/src:/app/client
      - ./${DATA_PATH}:/app/data
      - ./${CONFIG}:/app/client/project.yaml
      - ./${CERTIFICATE}:/app/client/certs/client-cert.pem
    device_requests:
      - capabilities:
          - "gpu"
    shm_size: '1g'
    ulimits:
      memlock: -1
      stack: 67108864
    stdin_open: true
    tty: true

  fedbird_2:
    environment:
      - CLIENT_NAME=${CLIENT_NAME}_2
    image: "fedbird:latest"
    env_file:
      - ./project.env
    working_dir: /app
    command: /bin/bash -c "fedn run client -d ${FEDN_REDUCER_HOST} -p ${FEDN_REDUCER_PORT} -n ${CLIENT_NAME}_2 -t ${FEDN_ALLIANCE_ADMIN_AUTH_TOKEN}" 
    volumes:
      - ./${COMPONENT_PATH}/src:/app/client
      - ./${DATA_PATH}:/app/data
      - ./${CONFIG}:/app/client/project.yaml
      - ./${CERTIFICATE}:/app/client/certs/client-cert.pem
    device_requests:
      - capabilities:
          - "gpu"
    shm_size: '1g'
    ulimits:
      memlock: -1
      stack: 67108864
    stdin_open: true
    tty: true
