version: '3.7'

services:
  
  combiner:
    environment:
      - PYTHONUNBUFFERED=0
      - GET_HOSTS_FROM=dns
      - ALLIANCE_UID=${ALLIANCE_UID}
      - FEDN_MINIO_HOST=${FEDN_MINIO_HOST}
      - FEDN_MINIO_PORT=${FEDN_MINIO_PORT}
      - FEDN_MINIO_ACCESS_KEY=${FEDN_MINIO_ACCESS_KEY}
      - FEDN_MINIO_SECRET_KEY=${FEDN_MINIO_SECRET_KEY}
      - FEDN_MONGO_USER=${FEDN_MONGO_USER}
      - FEDN_MONGO_PASSWORD=${FEDN_MONGO_PASSWORD}
      - FEDN_MONGO_HOST=${FEDN_MONGO_HOST}
      - FEDN_MONGO_PORT=${FEDN_MONGO_PORT}
    env_file:
      - ./project.env
    image: "fedbird/combiner_nvidia:exp"
    build:
      context: ${COMPONENT_PATH}
      dockerfile: ${PLATFORM}_platform.dockerfile
    working_dir: /app/combiner/src
    command: /bin/bash -c "/app/combiner/src/run.sh" 
    ports:
        - ${PORT}:${PORT}
    volumes:
      - ./${COMPONENT_PATH}/src:/app/combiner/src
      - ./${CONFIG}:/app/combiner/project.yaml
      - ./${CERTIFICATE}:/app/combiner/certs/reducer-cert.pem
    device_requests:
      - capabilities:
          - "gpu"
    shm_size: '1g'
    ulimits:
      memlock: -1
      stack: 67108864
    stdin_open: true
    tty: true

#volumes:
#  # CHANGE THIS IF YOU WANT TO PERSIST DATA ACROSS RUN's
#  minio-data:
