version: '3.7'

services:

  minio:
    image: minio/minio:latest
    hostname: minio
    environment:
      - GET_HOSTS_FROM=${GET_HOSTS_FROM}
      - MINIO_HOST=${FEDN_MINIO_HOST}
      - MINIO_PORT=${FEDN_MINIO_PORT}
      - MINIO_ACCESS_KEY=${FEDN_MINIO_ACCESS_KEY}
      - MINIO_SECRET_KEY=${FEDN_MINIO_SECRET_KEY}
    ports:
      - ${FEDN_MINIO_PORT}:${FEDN_MINIO_PORT}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://${FEDN_MINIO_HOST}:${FEDN_MINIO_PORT}/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    volumes:
      - minio-data:/data
    command: server /data

  mongo-express:
    container_name: mongo-express
    image: mongo-express:0.49.0
    depends_on:
      - mongo-database
    restart: always
    ports:
      - ${FEDN_MONGO_EXPRESS_PORT}:${FEDN_MONGO_EXPRESS_PORT}
    environment:
      - ME_CONFIG_MONGODB_SERVER=${FEDN_MONGO_HOST}
      - ME_CONFIG_MONGODB_PORT=${FEDN_MONGO_PORT}
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${FEDN_MONGO_USER}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${FEDN_MONGO_PASSWORD}
      - ME_CONFIG_BASICAUTH_USERNAME=${FEDN_MONGO_USER}
      - ME_CONFIG_BASICAUTH_PASSWORD=${FEDN_MONGO_PASSWORD}
    links:
    - "mongo-database"
    
  mongo-database:
    container_name: mongo
    image: mongo:4.4.1
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${FEDN_MONGO_USER}
      - MONGO_INITDB_DATABASE=${FEDN_PROJECT_NAME}
      - MONGO_INITDB_ROOT_PASSWORD=${FEDN_MONGO_PASSWORD}
    ports:
      - ${FEDN_MONGO_PORT}:${FEDN_MONGO_PORT}
    command: /usr/bin/mongod --port ${FEDN_MONGO_PORT} --bind_ip 0.0.0.0
    #stdin_open: true
    #tty: true

volumes:
  # CHANGE THIS IF YOU WANT TO PERSIST DATA ACROSS RUN's
  minio-data:
