version: '3.3'

services:

  minio:
    image: minio/minio:latest
    hostname: minio
    env_file:
      ./config/minio.env
    command: server /data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://minio:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    ports:
      - 9000:9000
    volumes:
      - minio-data:/data

  mongo:
    image: mongo:latest
    restart: always
    env_file:
      ./config/mongodb.env
    ports:
      - 6534:6534
    command: mongod --port 6534

  mongo-express:
    image: mongo-express:latest
    restart: always
    ports:
      - 8081:8081
    env_file:
      ./config/mongoexpress.env

volumes:
  # CHANGE THIS IF YOU WANT TO PERSIST DATA ACROSS RUN's
  minio-data:

