version: '3.3'
services:
  farallon3:
    environment:
      - GET_HOSTS_FROM=dns
    image: "fedbird-farallon3-client:latest"
    build:
      context: .
      dockerfile: ./Dockerfile_xavier
    working_dir: /app
    command: /bin/bash -c "fedn run client -in fedn-network.yaml"
    volumes:
      - ./data/client1/:/data/:ro

networks:
  default:
    external:
      name: fedn_default                              
