Project:
  project_name: fed-bird
  project_slug: fed-burd-rkq


Alliance:
  alliance_name: test-fed-bird
  alliance_uid: a1bdd2282-930a-44a8-96a3-15c05b5b34cb
  controller_host: combiner
  controller_port: 12080

  Repository:
    minio_host: minio
    minio_port: 9000
    minio_bucket: alliance
    minio_access_key: minio
    minio_secret_key: minio123
    minio_secure_mode: False
  
  Member:
    name: fed_bird
    entry_points:
      predict:
        command: python3 predict.py
      train:
        command: python3 train.py
      validate:
        command: python3 validate.py
