# Generated by Django 2.2.13 on 2020-09-24 19:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Combiner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('host', models.CharField(max_length=512)),
                ('port', models.IntegerField()),
                ('status', models.CharField(choices=[('S', 'Starting'), ('R', 'Ready'), ('I', 'Instructing'), ('C', 'Combining'), ('D', 'Decommission'), ('L', 'Lost')], default='S', max_length=2)),
                ('timeout', models.IntegerField(default=30)),
                ('timeout_lost', models.IntegerField(default=3600)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('storage_type', models.CharField(default='s3', max_length=512)),
                ('storage_hostname', models.CharField(max_length=512)),
                ('storage_port', models.IntegerField()),
                ('storage_access_key', models.CharField(max_length=512)),
                ('storage_secret_key', models.CharField(max_length=512)),
                ('storage_bucket', models.CharField(blank=True, default='models', max_length=512, null=True)),
                ('storage_secure_mode', models.BooleanField(default=False)),
                ('max_clients', models.IntegerField(default=8)),
                ('model_id', models.CharField(max_length=512)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CombinerConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('algorithm', models.CharField(default='fedavg', max_length=512)),
                ('round_timeout', models.IntegerField(default=180)),
                ('rounds', models.IntegerField(default=5)),
                ('clients_required', models.IntegerField(default=1)),
                ('clients_requested', models.IntegerField(default=None)),
                ('ml_framework', models.CharField(default='keras_sequential', max_length=512)),
                ('nr_local_epochs', models.IntegerField(default=1)),
                ('local_batch_size', models.IntegerField(default=32)),
                ('model_id', models.CharField(max_length=512)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('R', 'Ready'), ('E', 'Executing'), ('D', 'Done')], default='R', max_length=2)),
                ('combiner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='combiner.Combiner')),
            ],
        ),
    ]
